### ISSUE TITLE
TODO: User interactive creation of Maps and be able to save/load them with GUI

### ISSUE THREAD

**Issue by RickyC0** [Comp235-2024/Project#2]

**Comment by RickyC0** [comment]
- [ ] Create UI
- [ ] Make it resizable 
- [ ] Handle Clicks
- [ ] Place objects in the map
- [ ] Display placed objects on the screen
- [ ] Clear button
- [ ] Save button
