### ISSUE TITLE
TODO: Game engine that takes into account rounds, objective, progress and campaign progress

### ISSUE THREAD

**Issue by RickyC0** [Comp235-2024/Project#5]

**Comment by KapJ1coH** [comment]
- [ ] enable attack, move, inventory in one turn
- [ ] add character starts
- [ ] Enable the weapon visibility and shooting and range attack
